### ISSUE TITLE
How to use styles?

### ISSUE THREAD

**Issue by jozefrebjak** [tattersoftware/codeigniter4-menus#27]
I can't find how to use styles

**Comment by MGatner** [comment]
This library doesn't supply styling. Some instances (like the Breadcrumbs Menu) include classes compatible with Bootstrap, but you will still need to supply your own CSS files or framework. 

If you're looking for a CodeIgniter solution for managing style assets check out `Tatter\Assets` and/or `Tatter\Frontend`.
