### ISSUE TITLE
setActive($current, $root) working only for Home

### ISSUE THREAD

**Issue by jozefrebjak** [tattersoftware/codeigniter4-menus#28]
I can't get working another link to set active, it's working only for home route `/` for me, but it seems in a code that it's correct.

Here is my menu:

```php
/**
     * Returns the main menu
     *
     * @throws InvalidArgumentException
     * @throws ReflectionException
     * @throws RouterException
     */
    public function __toString(): string
    {
        return $this->builder
            ->html('<li class="menu-title"><span data-key="t-menu">Menu</span></li>')
            ->link(route_to('home'), '<i class="ri-home-4-line"></i> <span data-key="t-landing">Home</span><span class="badge badge-pill bg-danger" data-key="t-new">New</span>')
            ->link(route_to('client-list'), '<i class="ri-user-follow-line"></i> <span data-key="t-landing">Clients</span><span class="badge badge-pill bg-danger" data-key="t-new">New</span>')
            ->render();
```

It adds active to home route, but no to `client-list` route witch is `http://localhost/clients`. I am just extending Menu.

**Comment by MGatner** [comment]
Try modifying **src/Menu.php** to see what the actual values of `$current` and `$root` are, and compare them to your expected values on the route that isn't working. Most likely it is a mismatch of trailing slashes or something.

**Comment by jozefrebjak** [comment]
OK, I extended my `MainMenu` with `detectCurrent()` function and `$current` returns `http://localhost/clients` as expected and `$root` is `/` also as expected, but I can't figure why it's not adding an active class.

**Comment by MGatner** [comment]
I can't say for sure - I do remember the Spatie Menu being picky about this. I will play around with it when I'm on desktop.

**Comment by MGatner** [comment]
I can't recreate this. Is your code published somewhere that I could pull it to test with? A reminder I came across while testing: make sure the `baseUrl`, `forceGlobalSecureRequests`, and `indexPage` values in your App config (and **.env**) match what is showing in your browser

**Comment by jozefrebjak** [comment]
@MGatner Ok, I found an issue. It doesn't work with `route_to()` function, I must to specify routes with `site_url()` like:

```php
    public function __toString(): string
    {
        $home = '<i class="ri-home-4-line"></i><span data-key="t-landing">Home</span>';
        $clients = '<i class="ri-user-follow-line"></i><span data-key="t-landing">Clients</span>';

        $this->builder
            ->link(site_url('/'), $home)
            ->link(site_url('/clients'), $clients);

        return $this->builder->render();
    }
```

I also added to style `setActiveClassOnLink()` method and now it works as expected. Now I need to figure out how to deal with submenus.

**Comment by MGatner** [comment]
Ah! Good catch. This is expected, as `route_to()` returns the *relative path*:
https://github.com/codeigniter4/CodeIgniter4/blob/044ccbb1c1f51db407b6de05b5715b120a5d1972/system/Common.php#L898-L902

Spatie's `Menu` needs the full URL to match the entire URL:
https://github.com/spatie/menu/blob/272d2be017ccd7171285faa833ebb7bf7bd827ff/src/ActiveUrlChecker.php#L16

If you want to use `route_to()` just wrap it in the full `site_url()` call and it should work fine.
